/******** GENERATED FILE ********/
const files = {}
files["events"] = require("@factor/core-events").default
files["notify"] = require("@factor/plugin-notify").default
files["setting"] = require("@factor/app-settings").default
files["appDriver"] = require("@factor/app").default
files["db"] = require("@factor/core-db").default
files["endpoint"] = require("@factor/core-endpoint").default
files["storage"] = require("@factor/core-storage").default
files["user"] = require("@factor/core-user").default
files["auth"] = require("@factor/cms-user-auth").default
files["privsRequest"] = require("@factor/cms-user-role").default
files["googleAuth"] = require("@factor/service-google-auth").default
files["bulma"] = require("../src/index.js").default
files["time"] = require("@factor/tools-time").default
files["dashboard"] = require("@factor/cms-dashboard").default
files["cmsDashboardUsers"] = require("@factor/cms-dashboard-users").default
files["signin"] = require("@factor/cms-signin").default
files["componentsForm"] = require("@factor/ui-components-form").default
files["uiComponentsStandard"] = require("@factor/ui-components-standard").default
files["directivesStandard"] = require("@factor/ui-directives-standard").default
files["metatags"] = require("@factor/cms-metatags").default
files["pageTemplates"] = require("@factor/cms-page-templates").default
files["posts"] = require("@factor/cms-posts").default
files["markdown"] = require("@factor/tools-markdown").default
module.exports = files