/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CompiledUserConfig {
  routes:
    | "home"
    | "plugins"
    | "showcase"
    | "showcaseSingle"
    | "install"
    | "testing"
    | "blog"
    | "blogIndex"
    | "blogSingle"
    | "docs"
    | "docsIndex"
    | "docsSingle";
  paths?:
    | "/Users/arpowers/projects/factor/@plugins/plugin-notify/"
    | "/Users/arpowers/projects/factor/@plugins/plugin-highlight-code/"
    | "/Users/arpowers/projects/factor/@plugins/plugin-blog-engine/"
    | "/Users/arpowers/projects/factor/@plugins/plugin-docs-engine/";
  [k: string]: unknown;
}
