/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CompiledUserConfig {
  endpoints?:
    | "CurrentUser"
    | "Login"
    | "ManageUser"
    | "NewVerificationCode"
    | "ResetPassword"
    | "SendOneTimeCode"
    | "SetPassword"
    | "StartNewUser"
    | "UpdateCurrentUser"
    | "UserGoogleAuth"
    | "VerifyAccountEmail";
  routes:
    | "blog"
    | "blogIndex"
    | "blogSingle"
    | "docs"
    | "docsIndex"
    | "docsSingle"
    | "home"
    | "install"
    | "plugins"
    | "showcase"
    | "showcaseSingle"
    | "testing";
  paths?: string[];
  [k: string]: unknown;
}
