/* GENERATED FILE */
export default {
  app: () => import("@factor/app/index.js"),
  factorMeta: () => import("@factor/meta/index.js"),
  email: () => import("@factor/core-email/index"),
  endpoint: () => import("@factor/core-endpoint/index"),
  error: () => import("@factor/core-error/index.js"),
  storage: () => import("@factor/core-storage/index"),
  user: () => import("@factor/core-user/index"),
  userEmails: () => import("@factor/core-user-emails/index"),
  userRoles: () => import("@factor/core-user-roles/index"),
  ssrBar: () => import("@factor/plugin-ssr-bar/index.js"),
  post: () => import("@factor/post/index"),
  dashboard: () => import("@factor/dashboard/index.js"),
  coreUserDashboard: () => import("@factor/core-user-dashboard/index.js"),
  signin: () => import("@factor/dashboard-signin/index.js"),
  http: () => import("@factor/tools-http/index.js"),
  markdown: () => import("@factor/tools-markdown/index.js"),
  componentsForm: () => import("@factor/ui-components-form/index.js"),
  uiComponentsStandard: () => import("@factor/ui-components-standard/index.js"),
  directivesStandard: () => import("@factor/ui-directives-standard/index.js"),
  metatags: () => import("@factormeta-class/index.js"),
  templates: () => import("@factor/templates/index.js"),
  cwd: () => import("../index.js")
}
