app = 'fiction-gateway'
primary_region = 'lax'

[build]
dockerfile = './Dockerfile'
build-target = 'fiction-gateway'

[deploy]
strategy = 'bluegreen'

[http_service]
internal_port = 6565
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = [ 'app' ]

[http_service.concurrency]
type = 'requests'
hard_limit = 1000
soft_limit = 500

[[http_service.checks]]
timeout = '5s'
grace_period = "10s"
interval = "60s"
method = 'GET'
path = '/api/health'
tls_skip_verify = false

[[vm]]
size = 'performance-1x'
memory = '8gb'
cpu_kind = 'performance'
cpus = 1
