// import { resolve } from "path"
import { runCallbacks, addCallback } from "@factor/tools"
import { generateLoaders } from "@factor/cli/extension-loader"
// import commander from "commander"
// import dotenv from "dotenv"
// import execa from "execa"
// import inquirer from "inquirer"
// import listr from "listr"
// import log from "@factor/tools/logger"
// import { localhostUrl } from "@factor/tools/permalink"
// import aliasRequire from "./alias-require"
// import pkg from "./package"
// import transpiler from "./transpile"

console.log("run me")
