/* tslint:disable */
/**
 * Automatically generated file, do not modify by hand.
 */

export interface CompiledServiceConfig {
  commands: 'beacon' | 'dev' | 'rdev' | 'session' | 'tag'
  vars:
    | 'APP_PORT'
    | 'APP_URL'
    | 'AWS_ACCESS_KEY'
    | 'AWS_ACCESS_KEY_SECRET'
    | 'CLICKHOUSE_URL'
    | 'GOOGLE_CLIENT_ID'
    | 'GOOGLE_CLIENT_SECRET'
    | 'NODE_ENV'
    | 'POSTGRES_URL'
    | 'REDIS_URL'
    | 'REPLAY_PORT'
    | 'SERVER_PORT'
    | 'SERVER_URL'
    | 'SMTP_HOST'
    | 'SMTP_PASSWORD'
    | 'SMTP_USER'
    | 'TOKEN_SECRET'
  sessionFields: {
    sessionId: string
    anonymousId: string
    userId: string
    projectId: string
    organizationId: string
    timestamp: string
    value: number
    os: string
    browser: string
    deviceType: string
    locale: string
    ip: string
    isReturning: number
    isFake: number
    timezone: string
    duration: number
    startedAt: string
    endedAt: string
    entryPage: string
    exitPage: string
    scrollTotal: number
    keypressTotal: number
    clickTotal: number
    touchTotal: number
    moveTotal: number
    engageDuration: number
    replayDuration: number
    scrollDepth: number
    sessionNo: number
    version: string
    countryCode: string
    regionName: string
    cityName: string
    latitude: number
    longitude: number
    referrer: string
    referralSource: string
    referralCampaign: string
    referralMedium: string
    referralTerm: string
    referralContent: string
    referralTitle: string
    referralDescription: string
    referralCanonicalUrl: string
    referralImage: string
    pageCount: number
    isClosed: number
    isBounce: number
    totalEvents: number
    isRobot: number
    hasReplay: number
    totalGoalConversion: number
    totalConversion: number
    hasGoalConversion: number
    hasConversion: number
    eventCount: number
    [k: string]: unknown
  }
  tables: {
    factor_user:
      | 'userId'
      | 'email'
      | 'username'
      | 'googleId'
      | 'fullName'
      | 'firstName'
      | 'lastName'
      | 'role'
      | 'status'
      | 'site'
      | 'github'
      | 'githubFollowers'
      | 'twitter'
      | 'twitterFollowers'
      | 'facebook'
      | 'linkedin'
      | 'workSeniority'
      | 'workRole'
      | 'bio'
      | 'location'
      | 'hashedPassword'
      | 'emailVerified'
      | 'verificationCode'
      | 'codeExpiresAt'
      | 'picture'
      | 'avatar'
      | 'about'
      | 'gender'
      | 'birthday'
      | 'phoneNumber'
      | 'address'
      | 'meta'
      | 'settings'
      | 'profile'
      | 'invitedBy'
      | 'lastSeenAt'
      | 'createdAt'
      | 'updatedAt'
    kaption_event:
      | 'event'
      | 'gen'
      | 'isInternal'
      | 'type'
      | 'sessionId'
      | 'anonymousId'
      | 'userId'
      | 'projectId'
      | 'organizationId'
      | 'sentAt'
      | 'receivedAt'
      | 'timestamp'
      | 'reason'
      | 'conversion'
      | 'category'
      | 'label'
      | 'action'
      | 'selector'
      | 'value'
      | 'context'
      | 'meta'
      | 'traits'
      | 'trace'
      | 'pathname'
      | 'origin'
      | 'search'
      | 'os'
      | 'browser'
      | 'deviceType'
      | 'locale'
      | 'ip'
      | 'isReturning'
      | 'isFake'
      | 'timezone'
      | 'duration'
      | 'startedAt'
      | 'endedAt'
      | 'entryPage'
      | 'exitPage'
      | 'channel'
      | 'scrollTotal'
      | 'keypressTotal'
      | 'clickTotal'
      | 'touchTotal'
      | 'moveTotal'
      | 'engageDuration'
      | 'replayDuration'
      | 'scrollDepth'
      | 'sessionNo'
      | 'viewNo'
      | 'eventNo'
      | 'version'
      | 'eventId'
      | 'messageId'
      | 'countryCode'
      | 'regionName'
      | 'cityName'
      | 'latitude'
      | 'longitude'
      | 'referrer'
      | 'referralSource'
      | 'referralCampaign'
      | 'referralMedium'
      | 'referralTerm'
      | 'referralContent'
      | 'referralTitle'
      | 'referralDescription'
      | 'referralCanonicalUrl'
      | 'referralImage'
    kaption_session:
      | 'sessionId'
      | 'anonymousId'
      | 'userId'
      | 'projectId'
      | 'organizationId'
      | 'timestamp'
      | 'value'
      | 'os'
      | 'browser'
      | 'deviceType'
      | 'locale'
      | 'ip'
      | 'isReturning'
      | 'isFake'
      | 'timezone'
      | 'duration'
      | 'startedAt'
      | 'endedAt'
      | 'entryPage'
      | 'exitPage'
      | 'scrollTotal'
      | 'keypressTotal'
      | 'clickTotal'
      | 'touchTotal'
      | 'moveTotal'
      | 'engageDuration'
      | 'replayDuration'
      | 'scrollDepth'
      | 'sessionNo'
      | 'version'
      | 'countryCode'
      | 'regionName'
      | 'cityName'
      | 'latitude'
      | 'longitude'
      | 'referrer'
      | 'referralSource'
      | 'referralCampaign'
      | 'referralMedium'
      | 'referralTerm'
      | 'referralContent'
      | 'referralTitle'
      | 'referralDescription'
      | 'referralCanonicalUrl'
      | 'referralImage'
      | 'pageCount'
      | 'isClosed'
      | 'isBounce'
      | 'totalEvents'
      | 'isRobot'
      | 'hasReplay'
      | 'totalGoalConversion'
      | 'totalConversion'
      | 'hasGoalConversion'
      | 'hasConversion'
      | 'eventCount'
    [k: string]: unknown
  }
  [k: string]: unknown
}
