export const systemIcons = [
  { name: 'Home', iconId: 'home', iconClass: 'i-tabler-home' },
  { name: 'User', iconId: 'user', iconClass: 'i-tabler-user' },
  { name: 'Check', iconId: 'check', iconClass: 'i-tabler-check' },
  { name: 'Close', iconId: 'close', iconClass: 'i-tabler-x' },
  { name: 'Menu', iconId: 'menu', iconClass: 'i-tabler-menu-2' },
  { name: 'Search', iconId: 'search', iconClass: 'i-tabler-search' },
  { name: 'Settings', iconId: 'settings', iconClass: 'i-tabler-settings' },
  { name: 'Notification', iconId: 'notification', iconClass: 'i-tabler-bell' },
  { name: 'Email', iconId: 'email', iconClass: 'i-tabler-mail' },
  { name: 'Phone', iconId: 'phone', iconClass: 'i-tabler-phone' },
  { name: 'Lock', iconId: 'lock', iconClass: 'i-tabler-lock' },
  { name: 'Unlock', iconId: 'unlock', iconClass: 'i-tabler-lock-open' },
  { name: 'Star', iconId: 'star', iconClass: 'i-tabler-star' },
  { name: 'Heart', iconId: 'heart', iconClass: 'i-tabler-heart' },
  { name: 'Share', iconId: 'share', iconClass: 'i-tabler-share' },
  { name: 'Download', iconId: 'download', iconClass: 'i-tabler-download' },
  { name: 'Upload', iconId: 'upload', iconClass: 'i-tabler-upload' },
  { name: 'Trash', iconId: 'trash', iconClass: 'i-tabler-trash' },
  { name: 'Edit', iconId: 'edit', iconClass: 'i-tabler-edit' },
  { name: 'Calendar', iconId: 'calendar', iconClass: 'i-tabler-calendar' },
  { name: 'Clock', iconId: 'clock', iconClass: 'i-tabler-clock' },
  { name: 'Location', iconId: 'location', iconClass: 'i-tabler-map-pin' },
  { name: 'Camera', iconId: 'camera', iconClass: 'i-tabler-camera' },
  { name: 'Video', iconId: 'video', iconClass: 'i-tabler-video' },
  { name: 'Microphone', iconId: 'microphone', iconClass: 'i-tabler-microphone' },
  { name: 'Speaker', iconId: 'speaker', iconClass: 'i-tabler-volume' },
  { name: 'Mute', iconId: 'mute', iconClass: 'i-tabler-volume-off' },
  { name: 'Play', iconId: 'play', iconClass: 'i-tabler-player-play' },
  { name: 'Pause', iconId: 'pause', iconClass: 'i-tabler-player-pause' },
  { name: 'Stop', iconId: 'stop', iconClass: 'i-tabler-player-stop' },
  { name: 'Forward', iconId: 'forward', iconClass: 'i-tabler-player-track-next' },
  { name: 'Backward', iconId: 'backward', iconClass: 'i-tabler-player-track-prev' },
  { name: 'Shuffle', iconId: 'shuffle', iconClass: 'i-tabler-arrows-shuffle' },
  { name: 'Repeat', iconId: 'repeat', iconClass: 'i-tabler-repeat' },
  { name: 'List', iconId: 'list', iconClass: 'i-tabler-list' },
  { name: 'Grid', iconId: 'grid', iconClass: 'i-tabler-layout-grid' },
  { name: 'Filter', iconId: 'filter', iconClass: 'i-tabler-filter' },
  { name: 'Sort', iconId: 'sort', iconClass: 'i-tabler-sort-ascending' },
  { name: 'Chart', iconId: 'chart', iconClass: 'i-tabler-chart-bar' },
  { name: 'Pie Chart', iconId: 'pie-chart', iconClass: 'i-tabler-chart-pie' },
  { name: 'Line Chart', iconId: 'line-chart', iconClass: 'i-tabler-chart-line' },
  { name: 'Refresh', iconId: 'refresh', iconClass: 'i-tabler-refresh' },
  { name: 'Sync', iconId: 'sync', iconClass: 'i-tabler-refresh-dot' },
  { name: 'Link', iconId: 'link', iconClass: 'i-tabler-link' },
  { name: 'Unlink', iconId: 'unlink', iconClass: 'i-tabler-unlink' },
  { name: 'Attachment', iconId: 'attachment', iconClass: 'i-tabler-paperclip' },
  { name: 'Copy', iconId: 'copy', iconClass: 'i-tabler-copy' },
  { name: 'Paste', iconId: 'paste', iconClass: 'i-tabler-clipboard' },
  { name: 'Cut', iconId: 'cut', iconClass: 'i-tabler-cut' },
  { name: 'Bold', iconId: 'bold', iconClass: 'i-tabler-bold' },
  { name: 'Italic', iconId: 'italic', iconClass: 'i-tabler-italic' },
  { name: 'Underline', iconId: 'underline', iconClass: 'i-tabler-underline' },
  { name: 'Strikethrough', iconId: 'strikethrough', iconClass: 'i-tabler-strikethrough' },
  { name: 'Align Left', iconId: 'align-left', iconClass: 'i-tabler-align-left' },
  { name: 'Align Center', iconId: 'align-center', iconClass: 'i-tabler-align-center' },
  { name: 'Align Right', iconId: 'align-right', iconClass: 'i-tabler-align-right' },
  { name: 'Justify', iconId: 'align-justify', iconClass: 'i-tabler-align-justified' },
  { name: 'Indent', iconId: 'indent', iconClass: 'i-tabler-indent-increase' },
  { name: 'Outdent', iconId: 'outdent', iconClass: 'i-tabler-indent-decrease' },
  { name: 'List Ordered', iconId: 'list-ordered', iconClass: 'i-tabler-list-numbers' },
  { name: 'List Unordered', iconId: 'list-unordered', iconClass: 'i-tabler-list-check' },
  { name: 'Quote', iconId: 'quote', iconClass: 'i-tabler-quote' },
  { name: 'Code', iconId: 'code', iconClass: 'i-tabler-code' },
  { name: 'Image', iconId: 'image', iconClass: 'i-tabler-photo' },
  { name: 'Table', iconId: 'table', iconClass: 'i-tabler-table' },
  { name: 'Link Add', iconId: 'link-add', iconClass: 'i-tabler-link-plus' },
  { name: 'Emoji', iconId: 'emoji', iconClass: 'i-tabler-mood-smile' },
  { name: 'Undo', iconId: 'undo', iconClass: 'i-tabler-arrow-back-up' },
  { name: 'Redo', iconId: 'redo', iconClass: 'i-tabler-arrow-forward-up' },
  { name: 'Zoom In', iconId: 'zoom-in', iconClass: 'i-tabler-zoom-in' },
  { name: 'Zoom Out', iconId: 'zoom-out', iconClass: 'i-tabler-zoom-out' },
  { name: 'Full Screen', iconId: 'full-screen', iconClass: 'i-tabler-maximize' },
  { name: 'Exit Full Screen', iconId: 'exit-full-screen', iconClass: 'i-tabler-minimize' },
  { name: 'Print', iconId: 'print', iconClass: 'i-tabler-printer' },
  { name: 'Save', iconId: 'save', iconClass: 'i-tabler-device-floppy' },
  { name: 'Folder', iconId: 'folder', iconClass: 'i-tabler-folder' },
  { name: 'File', iconId: 'file', iconClass: 'i-tabler-file' },
  { name: 'Cloud', iconId: 'cloud', iconClass: 'i-tabler-cloud' },
  { name: 'Cloud Upload', iconId: 'cloud-upload', iconClass: 'i-tabler-cloud-upload' },
  { name: 'Cloud Download', iconId: 'cloud-download', iconClass: 'i-tabler-cloud-download' },
  { name: 'Database', iconId: 'database', iconClass: 'i-tabler-database' },
  { name: 'Server', iconId: 'server', iconClass: 'i-tabler-server' },
  { name: 'Wi-Fi', iconId: 'wifi', iconClass: 'i-tabler-wifi' },
  { name: 'Bluetooth', iconId: 'bluetooth', iconClass: 'i-tabler-bluetooth' },
  { name: 'Battery', iconId: 'battery', iconClass: 'i-tabler-battery' },
  { name: 'Power', iconId: 'power', iconClass: 'i-tabler-power' },
  { name: 'Lightbulb', iconId: 'lightbulb', iconClass: 'i-tabler-bulb' },
  { name: 'Plug', iconId: 'plug', iconClass: 'i-tabler-plug' },
  { name: 'Lightning Bolt', iconId: 'bolt', iconClass: 'i-tabler-bolt' },
  { name: 'Sun', iconId: 'sun', iconClass: 'i-tabler-sun' },
  { name: 'Moon', iconId: 'moon', iconClass: 'i-tabler-moon' },
  { name: 'Umbrella', iconId: 'umbrella', iconClass: 'i-tabler-umbrella' },
  { name: 'Eye', iconId: 'eye', iconClass: 'i-tabler-eye' },
  { name: 'Eye Off', iconId: 'eye-off', iconClass: 'i-tabler-eye-off' },
  { name: 'Bookmark', iconId: 'bookmark', iconClass: 'i-tabler-bookmark' },
  { name: 'Flag', iconId: 'flag', iconClass: 'i-tabler-flag' },
  { name: 'Pin', iconId: 'pin', iconClass: 'i-tabler-pin' },
  { name: 'Compass', iconId: 'compass', iconClass: 'i-tabler-compass' },
  { name: 'Map', iconId: 'map', iconClass: 'i-tabler-map' },
  { name: 'Ghost', iconId: 'ghost', iconClass: 'i-tabler-ghost' },
  { name: 'Navigation', iconId: 'navigation', iconClass: 'i-tabler-navigation' },
  { name: 'Car', iconId: 'car', iconClass: 'i-tabler-car' },
  { name: 'Airplane', iconId: 'airplane', iconClass: 'i-tabler-plane' },
  { name: 'Rocket', iconId: 'rocket', iconClass: 'i-tabler-rocket' },
  { name: 'Bicycle', iconId: 'bicycle', iconClass: 'i-tabler-bike' },
  { name: 'Train', iconId: 'train', iconClass: 'i-tabler-train' },
  { name: 'Ship', iconId: 'ship', iconClass: 'i-tabler-ship' },
  { name: 'Shopping Cart', iconId: 'shopping-cart', iconClass: 'i-tabler-shopping-cart' },
  { name: 'Credit Card', iconId: 'credit-card', iconClass: 'i-tabler-credit-card' },
  { name: 'Gift', iconId: 'gift', iconClass: 'i-tabler-gift' },
  { name: 'Tag', iconId: 'tag', iconClass: 'i-tabler-tag' },
  { name: 'Trophy', iconId: 'trophy', iconClass: 'i-tabler-trophy' },
  { name: 'Medal', iconId: 'medal', iconClass: 'i-tabler-medal' },
  { name: 'Crown', iconId: 'crown', iconClass: 'i-tabler-crown' },
  { name: 'Diamond', iconId: 'diamond', iconClass: 'i-tabler-diamond' },
  { name: 'Puzzle', iconId: 'puzzle', iconClass: 'i-tabler-puzzle' },
  { name: 'Palette', iconId: 'palette', iconClass: 'i-tabler-palette' },
  { name: 'Brush', iconId: 'brush', iconClass: 'i-tabler-brush' },
  { name: 'Paint', iconId: 'paint', iconClass: 'i-tabler-paint' },
  { name: 'Ruler', iconId: 'ruler', iconClass: 'i-tabler-ruler' },
  { name: 'Scissors', iconId: 'scissors', iconClass: 'i-tabler-scissors' },
  { name: 'Eraser', iconId: 'eraser', iconClass: 'i-tabler-eraser' },
  { name: 'Pencil', iconId: 'pencil', iconClass: 'i-tabler-pencil' },
  { name: 'Pen', iconId: 'pen', iconClass: 'i-tabler-ballpen' },
  { name: 'Highlighter', iconId: 'highlighter', iconClass: 'i-tabler-highlight' },
  { name: 'Notebook', iconId: 'notebook', iconClass: 'i-tabler-notebook' },
  { name: 'Book', iconId: 'book', iconClass: 'i-tabler-book' },
  { name: 'Books', iconId: 'books', iconClass: 'i-tabler-books' },
  { name: 'Library', iconId: 'library', iconClass: 'i-tabler-library' },
  { name: 'Graduation Cap', iconId: 'graduation-cap', iconClass: 'i-tabler-school' },
  { name: 'Globe', iconId: 'globe', iconClass: 'i-tabler-world' },
  { name: 'Planet', iconId: 'planet', iconClass: 'i-tabler-planet' },
  { name: 'Atom', iconId: 'atom', iconClass: 'i-tabler-atom' },
  { name: 'Experiment', iconId: 'experiment', iconClass: 'i-tabler-test-pipe' },
  { name: 'Microscope', iconId: 'microscope', iconClass: 'i-tabler-microscope' },
  { name: 'Add', iconId: 'add', iconClass: 'i-tabler-plus' },
  { name: 'Minus', iconId: 'minus', iconClass: 'i-tabler-minus' },
  { name: 'Info', iconId: 'info', iconClass: 'i-tabler-info-circle' },
  { name: 'Warning', iconId: 'warning', iconClass: 'i-tabler-alert-triangle' },
  { name: 'Error', iconId: 'error', iconClass: 'i-tabler-alert-circle' },
  { name: 'Success', iconId: 'success', iconClass: 'i-tabler-circle-check' },
  { name: 'Help', iconId: 'help', iconClass: 'i-tabler-help-circle' },
  { name: 'Question', iconId: 'question', iconClass: 'i-tabler-question-mark' },
  { name: 'Menu Dots', iconId: 'menu-dots', iconClass: 'i-tabler-dots-vertical' },
  { name: 'More', iconId: 'more', iconClass: 'i-tabler-dots-horizontal' },
  { name: 'Hamburger', iconId: 'hamburger', iconClass: 'i-tabler-menu' },
  { name: 'Arrow Up', iconId: 'arrow-up', iconClass: 'i-tabler-arrow-up' },
  { name: 'Arrow Up Right', iconId: 'arrow-up-right', iconClass: 'i-tabler-arrow-up-right' },
  { name: 'Arrow Up Left', iconId: 'arrow-up-left', iconClass: 'i-tabler-arrow-up-left' },
  { name: 'Arrow Down', iconId: 'arrow-down', iconClass: 'i-tabler-arrow-down' },
  { name: 'Arrow Down Right', iconId: 'arrow-down-right', iconClass: 'i-tabler-arrow-down-right' },
  { name: 'Arrow Down Left', iconId: 'arrow-down-left', iconClass: 'i-tabler-arrow-down-left' },
  { name: 'Arrow Left', iconId: 'arrow-left', iconClass: 'i-tabler-arrow-left' },
  { name: 'Arrow Right', iconId: 'arrow-right', iconClass: 'i-tabler-arrow-right' },
  { name: 'Chevron Up', iconId: 'chevron-up', iconClass: 'i-tabler-chevron-up' },
  { name: 'Chevron Down', iconId: 'chevron-down', iconClass: 'i-tabler-chevron-down' },
  { name: 'Chevron Left', iconId: 'chevron-left', iconClass: 'i-tabler-chevron-left' },
  { name: 'Chevron Right', iconId: 'chevron-right', iconClass: 'i-tabler-chevron-right' },
  { name: 'External Link', iconId: 'external-link', iconClass: 'i-tabler-external-link' },
  { name: 'Login', iconId: 'login', iconClass: 'i-tabler-login' },
  { name: 'Logout', iconId: 'logout', iconClass: 'i-tabler-logout' },
  { name: 'Profile', iconId: 'profile', iconClass: 'i-tabler-user-circle' },
  { name: 'Dashboard', iconId: 'dashboard', iconClass: 'i-tabler-dashboard' },
  { name: 'Analytics', iconId: 'analytics', iconClass: 'i-tabler-chart-line' },
  { name: 'Comments', iconId: 'comments', iconClass: 'i-tabler-messages' },
  { name: 'Chat', iconId: 'chat', iconClass: 'i-tabler-message-circle' },
  { name: 'Notifications', iconId: 'notifications', iconClass: 'i-tabler-bell-ringing' },
  { name: 'Cart', iconId: 'cart', iconClass: 'i-tabler-shopping-cart' },
  { name: 'Wishlist', iconId: 'wishlist', iconClass: 'i-tabler-heart' },
  { name: 'Compare', iconId: 'compare', iconClass: 'i-tabler-arrows-diff' },
  { name: 'Filter', iconId: 'filter', iconClass: 'i-tabler-adjustments' },
  { name: 'Sort', iconId: 'sort', iconClass: 'i-tabler-sort-ascending' },
  { name: 'Grid View', iconId: 'grid-view', iconClass: 'i-tabler-layout-grid' },
  { name: 'List View', iconId: 'list-view', iconClass: 'i-tabler-layout-list' },
  { name: 'Zoom', iconId: 'zoom', iconClass: 'i-tabler-zoom-in' },
  { name: 'Refresh', iconId: 'refresh', iconClass: 'i-tabler-refresh' },
  { name: 'Sync', iconId: 'sync', iconClass: 'i-tabler-refresh-dot' },
  { name: 'Dark Mode', iconId: 'dark-mode', iconClass: 'i-tabler-moon' },
  { name: 'Light Mode', iconId: 'light-mode', iconClass: 'i-tabler-sun' },
  { name: 'Language', iconId: 'language', iconClass: 'i-tabler-language' },
  { name: 'Translate', iconId: 'translate', iconClass: 'i-tabler-language' },
  { name: 'RSS', iconId: 'rss', iconClass: 'i-tabler-rss' },
  { name: 'Newsletter', iconId: 'newsletter', iconClass: 'i-tabler-mail' },
  { name: 'Sitemap', iconId: 'sitemap', iconClass: 'i-tabler-sitemap' },
  { name: 'Accessibility', iconId: 'accessibility', iconClass: 'i-tabler-accessible' },
  { name: 'Cookie', iconId: 'cookie', iconClass: 'i-tabler-cookie' },
  { name: 'Shield', iconId: 'shield', iconClass: 'i-tabler-shield' },
  { name: 'Verified', iconId: 'verified', iconClass: 'i-tabler-check-circle' },
  { name: 'Coupon', iconId: 'coupon', iconClass: 'i-tabler-ticket' },
  { name: 'DNA', iconId: 'dna', iconClass: 'i-tabler-dna' },
  { name: 'Magnet', iconId: 'magnet', iconClass: 'i-tabler-magnet' },
  { name: 'Stethoscope', iconId: 'stethoscope', iconClass: 'i-tabler-stethoscope' },
  { name: 'Pill', iconId: 'pill', iconClass: 'i-tabler-pill' },
  { name: 'Bandage', iconId: 'bandage', iconClass: 'i-tabler-bandage' },
  { name: 'Syringe', iconId: 'syringe', iconClass: 'i-tabler-vaccine' },
  { name: 'Thermometer', iconId: 'thermometer', iconClass: 'i-tabler-temperature' },
  { name: 'First Aid Kit', iconId: 'first-aid-kit', iconClass: 'i-tabler-first-aid-kit' },
  { name: 'Pulse', iconId: 'pulse', iconClass: 'i-tabler-heartbeat' },
  { name: 'Brain', iconId: 'brain', iconClass: 'i-tabler-brain' },
  { name: 'Accessibility', iconId: 'accessibility', iconClass: 'i-tabler-accessible' },
  { name: 'Yoga', iconId: 'yoga', iconClass: 'i-tabler-yoga' },
  { name: 'Dumbbell', iconId: 'dumbbell', iconClass: 'i-tabler-barbell' },
  { name: 'Bike', iconId: 'bike', iconClass: 'i-tabler-bike' },
  { name: 'Run', iconId: 'run', iconClass: 'i-tabler-run' },
  { name: 'Swimming', iconId: 'swim', iconClass: 'i-tabler-swimming' },
  { name: 'Tennis', iconId: 'tennis', iconClass: 'i-tabler-ball-tennis' },
  { name: 'Basketball', iconId: 'basketball', iconClass: 'i-tabler-ball-basketball' },
  { name: 'Football', iconId: 'football', iconClass: 'i-tabler-ball-football' },
  { name: 'Baseball', iconId: 'baseball', iconClass: 'i-tabler-ball-baseball' },
  { name: 'Volleyball', iconId: 'volleyball', iconClass: 'i-tabler-ball-volleyball' },
  { name: 'Golf', iconId: 'golf', iconClass: 'i-tabler-golf' },
  { name: 'Trophy', iconId: 'trophy', iconClass: 'i-tabler-trophy' },
  { name: 'Medal', iconId: 'medal', iconClass: 'i-tabler-medal' },
  { name: 'Ticket', iconId: 'ticket', iconClass: 'i-tabler-ticket' },
  { name: 'Microphone', iconId: 'microphone', iconClass: 'i-tabler-microphone' },
  { name: 'Headphones', iconId: 'headphones', iconClass: 'i-tabler-headphones' },
  { name: 'Guitar Pick', iconId: 'guitar-pick', iconClass: 'i-tabler-guitar-pick' },
  { name: 'Piano', iconId: 'piano', iconClass: 'i-tabler-piano' },
  { name: 'Drum', iconId: 'drum', iconClass: 'i-tabler-drum' },
  { name: 'Saxophone', iconId: 'saxophone', iconClass: 'i-tabler-music' },
  { name: 'Vinyl', iconId: 'vinyl', iconClass: 'i-tabler-vinyl' },
  { name: 'Movie', iconId: 'movie', iconClass: 'i-tabler-movie' },
  { name: 'Theater', iconId: 'theater', iconClass: 'i-tabler-theater' },
  { name: 'Broadcast', iconId: 'broadcast', iconClass: 'i-tabler-broadcast' },
  { name: 'Podcast', iconId: 'podcast', iconClass: 'i-tabler-podcast' },
  { name: 'Radio', iconId: 'radio', iconClass: 'i-tabler-radio' },
  { name: 'Newspaper', iconId: 'newspaper', iconClass: 'i-tabler-news' },
  { name: 'Megaphone', iconId: 'megaphone', iconClass: 'i-tabler-speakerphone' },
  { name: 'Presentation', iconId: 'presentation', iconClass: 'i-tabler-presentation' },
  { name: 'Projector', iconId: 'projector', iconClass: 'i-tabler-device-projector' },
  { name: 'Video Camera', iconId: 'video-camera', iconClass: 'i-tabler-video' },
  { name: 'Photography', iconId: 'photography', iconClass: 'i-tabler-camera' },
  { name: 'Gallery', iconId: 'gallery', iconClass: 'i-tabler-photo-album' },
  { name: 'Paint Brush', iconId: 'paint-brush', iconClass: 'i-tabler-paint-brush' },
  { name: 'Palette', iconId: 'palette', iconClass: 'i-tabler-palette' },
  { name: 'Color Picker', iconId: 'color-picker', iconClass: 'i-tabler-color-picker' },
  { name: 'Eyedropper', iconId: 'eyedropper', iconClass: 'i-tabler-color-picker' },
  { name: 'Magic Wand', iconId: 'magic-wand', iconClass: 'i-tabler-wand' },
  { name: 'Crop', iconId: 'crop', iconClass: 'i-tabler-crop' },
  { name: 'Layers', iconId: 'layers', iconClass: 'i-tabler-layers-intersect' },
  { name: 'Mask', iconId: 'mask', iconClass: 'i-tabler-mask' },
  { name: 'Vector', iconId: 'vector', iconClass: 'i-tabler-vector-triangle' },
  { name: '3D Cube', iconId: '3d-cube', iconClass: 'i-tabler-cube' },
  { name: 'Augmented Reality', iconId: 'augmented-reality', iconClass: 'i-tabler-augmented-reality' },
  { name: 'Joystick', iconId: 'joystick', iconClass: 'i-tabler-device-gamepad' },
  { name: 'Puzzle', iconId: 'puzzle', iconClass: 'i-tabler-puzzle' },
  { name: 'Chess', iconId: 'chess', iconClass: 'i-tabler-chess' },
  { name: 'Dice', iconId: 'dice', iconClass: 'i-tabler-dice' },
  { name: 'Cards', iconId: 'cards', iconClass: 'i-tabler-cards' },
  { name: 'Telescope', iconId: 'telescope', iconClass: 'i-tabler-telescope' },
  { name: 'Satellite', iconId: 'satellite', iconClass: 'i-tabler-satellite' },
  { name: 'Rocket', iconId: 'rocket', iconClass: 'i-tabler-rocket' },
  { name: 'UFO', iconId: 'ufo', iconClass: 'i-tabler-ufo' },
  { name: 'Robot', iconId: 'robot', iconClass: 'i-tabler-robot' },
  { name: 'Cpu', iconId: 'cpu', iconClass: 'i-tabler-cpu' },
  { name: 'Keyboard', iconId: 'keyboard', iconClass: 'i-tabler-keyboard' },
  { name: 'Mouse', iconId: 'mouse', iconClass: 'i-tabler-mouse' },
  { name: 'Printer', iconId: 'printer', iconClass: 'i-tabler-printer' },
  { name: 'Scanner', iconId: 'scanner', iconClass: 'i-tabler-scan' },
  { name: 'Calculator', iconId: 'calculator', iconClass: 'i-tabler-calculator' },
  { name: 'USB', iconId: 'usb', iconClass: 'i-tabler-usb' },
  { name: 'QR Code', iconId: 'qr-code', iconClass: 'i-tabler-qrcode' },
  { name: 'Barcode', iconId: 'barcode', iconClass: 'i-tabler-barcode' },
  { name: 'Facebook', iconId: 'facebook', iconClass: 'i-tabler-brand-facebook' },
  { name: 'X', iconId: 'x', iconClass: 'i-tabler-brand-x' },
  { name: 'Instagram', iconId: 'instagram', iconClass: 'i-tabler-brand-instagram' },
  { name: 'LinkedIn', iconId: 'linkedin', iconClass: 'i-tabler-brand-linkedin' },
  { name: 'YouTube', iconId: 'youtube', iconClass: 'i-tabler-brand-youtube' },
  { name: 'TikTok', iconId: 'tiktok', iconClass: 'i-tabler-brand-tiktok' },
  { name: 'WhatsApp', iconId: 'whatsapp', iconClass: 'i-tabler-brand-whatsapp' },
  { name: 'Telegram', iconId: 'telegram', iconClass: 'i-tabler-brand-telegram' },
  { name: 'Discord', iconId: 'discord', iconClass: 'i-tabler-brand-discord' },
  { name: 'Slack', iconId: 'slack', iconClass: 'i-tabler-brand-slack' },
  { name: 'GitHub', iconId: 'github', iconClass: 'i-tabler-brand-github' },
  { name: 'GitLab', iconId: 'gitlab', iconClass: 'i-tabler-brand-gitlab' },
  { name: 'Dribbble', iconId: 'dribbble', iconClass: 'i-tabler-brand-dribbble' },
  { name: 'Behance', iconId: 'behance', iconClass: 'i-tabler-brand-behance' },
  { name: 'Medium', iconId: 'medium', iconClass: 'i-tabler-brand-medium' },
  { name: 'PayPal', iconId: 'paypal', iconClass: 'i-tabler-brand-paypal' },
  { name: 'Stripe', iconId: 'stripe', iconClass: 'i-tabler-brand-stripe' },
  { name: 'Apple', iconId: 'apple', iconClass: 'i-tabler-brand-apple' },
  { name: 'Android', iconId: 'android', iconClass: 'i-tabler-brand-android' },
  { name: 'Windows', iconId: 'windows', iconClass: 'i-tabler-brand-windows' },
  { name: 'Google', iconId: 'google', iconClass: 'i-tabler-brand-google' },
  { name: 'Amazon', iconId: 'amazon', iconClass: 'i-tabler-brand-amazon' },
  { name: 'Netflix', iconId: 'netflix', iconClass: 'i-tabler-brand-netflix' },
  { name: 'Spotify', iconId: 'spotify', iconClass: 'i-tabler-brand-spotify' },
  { name: 'Soundcloud', iconId: 'soundcloud', iconClass: 'i-tabler-brand-soundcloud' },
  { name: 'Airbnb', iconId: 'airbnb', iconClass: 'i-tabler-brand-airbnb' },
  { name: 'Uber', iconId: 'uber', iconClass: 'i-tabler-brand-uber' },
  { name: 'Figma', iconId: 'figma', iconClass: 'i-tabler-brand-figma' },
  { name: 'Sketch', iconId: 'sketch', iconClass: 'i-tabler-brand-sketch' },
] as const

export type IconId = typeof systemIcons[number]['iconId']
