# fly.toml app configuration file generated for fiction-gateway-proxy on 2025-02-04T00:37:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fiction-gateway-proxy'
primary_region = 'lax'

[build]
dockerfile = './Dockerfile'

[deploy]
strategy = 'immediate'
wait_timeout = '30s'

[[mounts]]
source = 'caddy_data'
destination = '/data'
initial_size = '1GB'

[[services]]
protocol = 'tcp'
internal_port = 443
auto_stop_machines = 'off'
min_machines_running = 1

[[services.ports]]
port = 443

[[services.tcp_checks]]
interval = '30s'
timeout = '10s'
grace_period = '45s'

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2
