app = 'fiction-gateway-proxy'
primary_region = 'lax'

[build]
dockerfile = './Dockerfile'

[deploy]
strategy = 'immediate'
wait_timeout = '30s'

# Persistent volume for certificates
[[mounts]]
source = 'caddy_data'
destination = '/data'
initial_size = '1GB'

# HTTP Service
[[services]]
protocol = "tcp"
internal_port = 80
auto_stop_machines = false
min_machines_running = 1

[[services.ports]]
port = 80
handlers = []

# HTTPS Service
[[services]]
protocol = "tcp"
internal_port = 443
auto_stop_machines = false
min_machines_running = 1

[[services.ports]]
port = 443
handlers = []

[metrics]
port = 2019
path = "/metrics"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2
