export default {
  core: {
    components: {
      btn: (): Promise<any> => import("./el/btn.vue"),
      dashboardBtn: (): Promise<any> => import("./dashboard/btn.vue"),
      btnBase: (): Promise<any> => import("./el/btn-base.vue"),
      link: (): Promise<any> => import("./el/link.vue"),
      spinner: (): Promise<any> => import("./el/spinner.vue"),
      modal: (): Promise<any> => import("./el/modal.vue"),
      modalApp: (): Promise<any> => import("./el/modal.vue"),
      factorLightbox: (): Promise<any> => import("./el/lightbox.vue"),
      factorMenu: (): Promise<any> => import("./el/menu.vue"),
      factorIcon: (): Promise<any> => import("./el/icon.vue"),
      factorAvatar: (): Promise<any> => import("./el/avatar.vue"),
    },
    forms: {
      factorForm: (): Promise<any> => import("./form/form.vue"),
      factorInputWrap: (): Promise<any> => import("./form/wrap-input.vue"),
      factorInputEmail: (): Promise<any> => import("./form/email.vue"),
      factorInputTags: (): Promise<any> => import("./form/tags.vue"),
      factorInputEditor: (): Promise<any> => import("./form/editor.vue"),
      factorInputDate: (): Promise<any> => import("./form/date.vue"),
      factorInputPassword: (): Promise<any> => import("./form/password.vue"),
      factorInputText: (): Promise<any> => import("./form/text.vue"),
      factorInputTextarea: (): Promise<any> => import("./form/textarea.vue"),
      factorInputPhone: (): Promise<any> => import("./form/phone.vue"),
      factorInputCheckbox: (): Promise<any> => import("./form/checkbox.vue"),
      factorInputSortable: (): Promise<any> => import("./form/sortable.vue"),
      factorInputBirthday: (): Promise<any> => import("./form/birthday.vue"),
      factorInputImageUpload: (): Promise<any> => import("./form/image-upload.vue"),
      factorInputSelect: (): Promise<any> => import("./form/select.vue"),
      factorInputSubmit: (): Promise<any> => import("./form/submit.vue"),
    },
    dashboard: {
      dashboardWrapper: (): Promise<any> => import("./dashboard/wrapper.vue"),
      managerDropdown: (): Promise<any> => import("./dashboard/el/manager-dd.vue"),
      dashboardPanel: (): Promise<any> => import("./dashboard/panel.vue"),
      dashboardPage: (): Promise<any> => import("./dashboard/page.vue"),
      dashboardFooter: (): Promise<any> => import("./dashboard/footer.vue"),
      dashboardListPost: (): Promise<any> => import("./dashboard/list-post.vue"),
      dashboardListItem: (): Promise<any> => import("./dashboard/list-item.vue"),
      dashboardListEmpty: (): Promise<any> => import("./dashboard/list-empty.vue"),
      dashboardListControls: (): Promise<any> => import("./dashboard/list-controls.vue"),
      dashboardInput: (): Promise<any> => import("./dashboard/input.vue"),
      dashboardListFooter: (): Promise<any> => import("./dashboard/list-footer.vue"),
      dashboardUserList: (): Promise<any> => import("./dashboard/user-list.vue"),
      dashboardUserCard: (): Promise<any> => import("./dashboard/user-card.vue"),
    },
  },
}
