describe("core components", () => {
  it.todo("renders link")
  it.todo("renders icon")
  it.todo("renders btn")
  it.todo("renders loading-ring")
  it.todo("renders modal")
  it.todo("renders avatar")
  it.todo("renders lightbox")
  it.todo("renders menu")
})
