/******** GENERATED FILE ********/
const files = {}
files["storageServer"] = require("@factor/core-storage/server").default
files["endpointServer"] = require("@factor/core-endpoint/server").default
files["setting"] = require("@factor/app-settings").default
files["setup"] = require("@factor/build-setup").default
files["webpack"] = require("@factor/build-webpack").default
files["serverDev"] = require("@factor/server-dev").default
files["dbServer"] = require("@factor/core-db/server").default
files["emailServer"] = require("@factor/core-email/server").default
files["postsServer"] = require("@factor/post/server").default
files["error"] = require("@factor/core-error").default
files["appFallbacks"] = require("@factor/app-fallbacks").default
files["userServer"] = require("@factor/core-user/server").default
files["userEmailsServer"] = require("@factor/core-user-emails/server").default
files["userRolesServer"] = require("@factor/core-user-roles/server").default
files["server"] = require("@factor/server").default
files["http"] = require("@factor/tools-http").default
files["time"] = require("@factor/tools-time").default
files["dashboard"] = require("@factor/dashboard").default
files["directivesStandard"] = require("@factor/ui-directives-standard").default
files["templatesServer"] = require("@factor/post-page-templates/server").default
files["cwd"] = require("../src/index.js").default
module.exports = files