name: PUBLISH

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      cmd:
        description: Command
        required: true
        type: choice
        options:
          - deploy
          - test
      tags:
        description: Tags
        required: false
        type: string

permissions:
  contents: write
  issues: write

env:
  CI: true
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APOLLO_API_KEY: ${{ secrets.APOLLO_API_KEY }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_BUCKET_MEDIA: ${{ secrets.AWS_BUCKET_MEDIA }}
  REDIS_URL: redis://localhost:6379
  CLICKHOUSE_URL: http://default:@localhost:8123
  POSTGRES_URL: http://test:test@localhost:5432/test
  STRIPE_SECRET_KEY_TEST: ${{ secrets.STRIPE_SECRET_KEY_TEST }}
  STRIPE_PUBLIC_KEY_TEST: ${{ secrets.STRIPE_PUBLIC_KEY_TEST }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  PROXYCURL_API_KEY: ${{ secrets.PROXYCURL_API_KEY }}
  XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  BETTER_STACK_SOURCE_TOKEN: ${{ secrets.BETTER_STACK_SOURCE_TOKEN }}
  BUILD_COMMIT: ${{ github.sha }}
  BUILD_TIME: ${{ github.event.repository.updated_at }}
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_BRANCH: ${{ github.ref_name }}
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  MIXPANEL_API_SECRET: ${{ secrets.MIXPANEL_API_SECRET }}
  AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
  SENTRY_PUBLIC_DSN: ${{ secrets.SENTRY_PUBLIC_DSN }}

jobs:

  check-flags:
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ contains(github.event.head_commit.message, '-d') }}
      should-release: ${{ contains(github.event.head_commit.message, '-r') }}
    steps:
      - run: echo "Checking deployment flags"

  prepare:
    needs: check-flags
    if: contains(github.event.head_commit.message, 'skip') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm i && pnpm rebuild --recursive

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

  type-check:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}
      - run: npm run types:ci

  unit-tests:
    needs: [prepare]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: |
          npm exec -- vitest run unit -u

  unit-special:
    needs: [prepare]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: |
          npm exec -- vitest run spot -u --passWithNoTests
          npm exec -- vitest run debug -u --passWithNoTests
          npm exec -- vitest run aix -u --passWithNoTests
          npm exec -- vitest run envi -u --passWithNoTests

  integration-tests:
    needs: [prepare]
    runs-on: ubuntu-latest
    env:
      REDIS_URL: redis://localhost:6379
      CLICKHOUSE_URL: http://default:@localhost:8123
      POSTGRES_URL: http://test:test@localhost:5432/test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: |
          npm exec -- vitest run flow -u --no-file-parallelism --passWithNoTests

  e2e-tests:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: npm exec -- vitest run uiux -u --no-file-parallelism

  card-ui-tests:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: npm exec -- vitest run card-ui -u --no-file-parallelism

  build-tests:
    needs: [prepare]
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: npm exec -- fiction run bundle
      - run: npm exec -- vitest run build -u --no-file-parallelism
      - uses: actions/cache/save@v4
        with:
          path: |
            @fiction/*/dist
            @fiction/*/.fiction
          key: build-output-${{ github.sha }}

  render:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      # Restore built dist folders
      - uses: actions/cache/restore@v4
        with:
          path: |
            @fiction/*/dist
            @fiction/*/.fiction
          key: build-output-${{ github.sha }}

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - run: npm exec -- fiction run render

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set up DNS for subdomain testing
        run: |
          echo "127.0.0.1 test.lan.com" | sudo tee -a /etc/hosts

      - name: Run Docker Compose (DB)
        run: docker compose -f ./docker/docker-compose.yml pull && docker compose -f ./docker/docker-compose.yml up --build -d

      - name: Create Tables
        run: npm -w @fiction/www exec -- fiction run generate

      - name: Verify Distribution Files
        run: npm exec -- vitest run dist -u

      # Save combined build and render output
      - uses: actions/cache/save@v4
        with:
          path: |
            @fiction/*/dist
            @fiction/*/.fiction
          key: render-output-${{ github.sha }}

  deploy-gateway:
    needs: [type-check, unit-tests, unit-special, integration-tests, e2e-tests, card-ui-tests, check-flags, render]
    if: ${{ needs.check-flags.outputs.should-deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0

      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: actions/cache/restore@v4
        with:
          path: |
            @fiction/*/dist
            @fiction/*/.fiction
          key: render-output-${{ github.sha }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - run: pnpm add cross-env --global

      - name: Deploy to Production
        run: |
          cross-env DOMAIN=fiction APP=gateway npm run deploy

  deploy-app:
    needs: [type-check, unit-tests, unit-special, integration-tests, e2e-tests, card-ui-tests, check-flags, render]
    if: ${{ needs.check-flags.outputs.should-deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0

      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: actions/cache/restore@v4
        with:
          path: |
            @fiction/*/dist
            @fiction/*/.fiction
          key: render-output-${{ github.sha }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - run: pnpm add cross-env --global

      - name: Deploy to Production
        run: |
          cross-env DOMAIN=fiction APP=www npm run deploy

  deploy-beacon:
    needs: [type-check, unit-tests, unit-special, integration-tests, e2e-tests, card-ui-tests, check-flags, render]
    if: ${{ needs.check-flags.outputs.should-deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0

      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: actions/cache/restore@v4
        with:
          path: |
            @fiction/*/dist
            @fiction/*/.fiction
          key: render-output-${{ github.sha }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - run: pnpm add cross-env --global

      - name: Deploy to Production
        run: |
          cross-env DOMAIN=fiction APP=beacon npm run deploy

  release:
    needs: [deploy-app, check-flags]
    if: ${{ needs.check-flags.outputs.should-release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - uses: actions/setup-node@v4
        with:
          node-version: 23.9.0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install GH CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - run: npm run i:lockfile && npm run release

  notify:
    needs: [unit-tests, integration-tests, e2e-tests, deploy-app, deploy-gateway, release]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "icon_emoji": "${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}",
              "username": "supereon",
              "channel": "#notify",
              "text": "Workflow *${{ github.workflow }}* on *${{ github.ref }}* (commit: ${{ github.sha }}) completed with status: *${{ job.status }}*. <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-discord:
    needs: [unit-tests, unit-special, integration-tests, e2e-tests, card-ui-tests, build-tests, deploy-app, deploy-gateway, deploy-beacon]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEV }}
        with:
          args: |
            ${{ contains(needs.*.result, 'failure') && '❌ **FAILED**' || '✅ **SUCCESS**' }} - Workflow **${{ github.workflow }}** on **${{ github.ref_name }}** (commit: `${{ github.sha }}`)
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
