// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./shim.d.ts" />

if (typeof window !== "undefined") window.process.env = {}
console.log("hello")
export * from "@factor/types"
export * from "./_"
export * from "./endpoint"
export * from "./error"
export * from "./event"
export * from "./excerpt"
export * from "./extend"
export * from "./geo"
export * from "./hook"
export * from "./jwt"
export * from "./logger"
export * from "./markdown"
export * from "./meta"
export * from "./router"
export * from "./store"
export * from "./time"
export * from "./url"
export * from "./user"
export * from "./userCurrent"
export * from "./utils"
export * from "./ui"
export * from "./validation"
export * from "./activity"
export * from "./number"
export * from "./local"
export * from "./cookie"
