import { expect, it, describe } from "vitest"
import * as mainFile from "@factor/site"
import { setupApp } from ".."
describe("server entry handling", () => {
  it("gets entry and runs server function if exists", async () => {
    const config = await setupApp({ mainFile })

    expect(config.variables?.TEST_BLOG_PLUGIN).toBe(undefined)
    expect(config.server).toBe(undefined)
    expect(config.plugins).toBe(undefined)
    expect(config).toMatchInlineSnapshot(`
      {
        "paths": [
          "/Users/arpowers/projects/factor/@plugins/plugin-stripe/",
          "/Users/arpowers/projects/factor/@plugins/plugin-notify/",
          "/Users/arpowers/projects/factor/@plugins/plugin-highlight-code/",
          "/Users/arpowers/projects/factor/@plugins/plugin-blog-engine/",
          "/Users/arpowers/projects/factor/@plugins/plugin-docs-engine/",
        ],
        "port": "5030",
        "portApp": undefined,
        "routes": [
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "home",
            "niceName": "Home",
            "parent": undefined,
            "path": "/",
            "priority": 100,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "plugins",
            "niceName": "Plugins",
            "parent": undefined,
            "path": "/plugins",
            "priority": 100,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "showcase",
            "niceName": "Showcase",
            "parent": undefined,
            "path": "/showcase",
            "priority": 100,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "showcaseSingle",
            "niceName": "Showcase Item",
            "parent": undefined,
            "path": "/showcase/:slug",
            "priority": 100,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "install",
            "niceName": "Install",
            "parent": undefined,
            "path": "/install",
            "priority": 100,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "testing",
            "niceName": "Testing",
            "parent": undefined,
            "path": "/testing",
            "priority": 100,
          },
          AppRoute {
            "children": [
              AppRoute {
                "children": [],
                "component": [Function],
                "external": undefined,
                "icon": undefined,
                "isActive": undefined,
                "menus": [],
                "meta": undefined,
                "name": "blogIndex",
                "niceName": "Blog Index",
                "parent": "blog",
                "path": "/blog",
                "priority": 200,
              },
              AppRoute {
                "children": [],
                "component": [Function],
                "external": undefined,
                "icon": undefined,
                "isActive": undefined,
                "menus": [],
                "meta": undefined,
                "name": "blogSingle",
                "niceName": "Blog Single",
                "parent": "blog",
                "path": "/blog/:slug",
                "priority": 200,
              },
            ],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "blog",
            "niceName": "Blog",
            "parent": undefined,
            "path": "/blog",
            "priority": 100,
          },
          AppRoute {
            "children": [
              AppRoute {
                "children": [],
                "component": [Function],
                "external": undefined,
                "icon": undefined,
                "isActive": undefined,
                "menus": [],
                "meta": undefined,
                "name": "docsIndex",
                "niceName": "Docs Index",
                "parent": "docs",
                "path": "/docs",
                "priority": 200,
              },
              AppRoute {
                "children": [],
                "component": [Function],
                "external": undefined,
                "icon": undefined,
                "isActive": undefined,
                "menus": [],
                "meta": undefined,
                "name": "docsSingle",
                "niceName": "Docs Single",
                "parent": "docs",
                "path": "/docs/:slug",
                "priority": 200,
              },
            ],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "docs",
            "niceName": "Docs",
            "parent": undefined,
            "path": "/docs",
            "priority": 100,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "blogIndex",
            "niceName": "Blog Index",
            "parent": "blog",
            "path": "/blog",
            "priority": 200,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "blogSingle",
            "niceName": "Blog Single",
            "parent": "blog",
            "path": "/blog/:slug",
            "priority": 200,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "docsIndex",
            "niceName": "Docs Index",
            "parent": "docs",
            "path": "/docs",
            "priority": 200,
          },
          AppRoute {
            "children": [],
            "component": [Function],
            "external": undefined,
            "icon": undefined,
            "isActive": undefined,
            "menus": [],
            "meta": undefined,
            "name": "docsSingle",
            "niceName": "Docs Single",
            "parent": "docs",
            "path": "/docs/:slug",
            "priority": 200,
          },
        ],
        "sitemaps": [
          {
            "paths": [
              "/blog/factorjs-version-3-released",
            ],
            "topic": "posts",
          },
          {
            "paths": [
              "/docs/introduction",
              "/docs/core-concepts",
              "/docs/quickstart",
              "/docs/configuration",
              "/docs/dev-server",
              "/docs/upgrading",
              "/docs/styling",
              "/docs/template",
              "/docs/meta-tags",
              "/docs/routes",
              "/docs/app-component",
              "/docs/store",
              "/docs/public-folder",
              "/docs/pre-render",
              "/docs/deploy-server",
              "/docs/endpoints",
              "/docs/server-config",
              "/docs/sitemaps",
              "/docs/using-plugins",
            ],
            "topic": "docs",
          },
        ],
      }
    `)
  })
})
